# Generated by Django 3.2.9 on 2022-02-02 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_occurrence', models.DateField()),
                ('periodicity_occurrence', models.IntegerField(choices=[(1, 'Mensal'), (2, 'Bimestral'), (3, 'Trimestral'), (4, 'Semestral'), (5, 'Anual')], default=5)),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
