# Generated by Django 3.2.9 on 2022-02-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bank_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expanse',
            name='user',
        ),
    ]
