# Generated by Django 3.2.9 on 2022-02-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_expanse_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Liquidada')], default=1)),
                ('value', models.FloatField()),
                ('bank_account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bankaccount')),
                ('expanse_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.expanse')),
            ],
        ),
    ]
