# Generated by Django 3.2.9 on 2022-02-15 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Banco'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Conta Bancária', 'verbose_name_plural': 'Contas Bancárias'},
        ),
        migrations.AlterModelOptions(
            name='expanse',
            options={'verbose_name': 'Despesa'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transação'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Logomarca'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.FloatField(verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='expanse',
            name='next_occurrence',
            field=models.DateField(verbose_name='Próxima Ocorrência'),
        ),
        migrations.AlterField(
            model_name='expanse',
            name='periodicity_occurrence',
            field=models.IntegerField(choices=[(1, 'Mensal'), (2, 'Bimestral'), (3, 'Trimestral'), (4, 'Semestral'), (5, 'Anual')], default=5, verbose_name='Periodicidade'),
        ),
        migrations.AlterField(
            model_name='expanse',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bankaccount', verbose_name='Conta Bancária'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expanse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.expanse', verbose_name='Despesa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_date',
            field=models.DateField(verbose_name='Data de Liquidação'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Liquidada')], default=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
