# Generated by Django 3.2.9 on 2022-02-16 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220215_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='expanse',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.bank', verbose_name='Banco'),
        ),
    ]
