# Generated by Django 3.2.9 on 2022-02-16 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220215_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='expanse',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
    ]
